# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    # Configure provisioning
    # using a specific IP.
    config.vm.network "private_network", ip: "192.168.56.16"
  end
  